version: "1.0"
projectName: SIQA_GIT_191225Project
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: fld_100564802_stage00.projects.flb53ef3e04c284b04ae6755156aa7d9fc.integrations:conntest
    type: flow
    stepId: /1
    reference: fld_100564802_stage00.projects.flb53ef3e04c284b04ae6755156aa7d9fc.WmPackageServiceProvider.SIQACloudStreamsTests:connetorOperations
  - name: fld_100564802_stage00.projects.flb53ef3e04c284b04ae6755156aa7d9fc.integrations:conntest
    type: flow
    stepId: /2
    reference: fld_100564802_stage00.projects.flb53ef3e04c284b04ae6755156aa7d9fc.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
  - name: Call_deepclonetest
    type: workflow
    uid: fl708576860f0a436ea370ede2089db3e2
    stepId: a0
    reference: project.siqa_git_191225.integrations:deepclonetest
- runtimeAlias: SIQA_ERT_2025
  assets:
  - name: fld_100564802_stage00.projects.flb53ef3e04c284b04ae6755156aa7d9fc.integrations:conntest
    type: flow
    stepId: /0
    reference: fld_100564802_stage00.projects.flb53ef3e04c284b04ae6755156aa7d9fc.WmPackageServiceProvider.GB_1:readGlobalvariable
