version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_191225Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
- name: WmSalesforceProvider
  version: 12.0.0.0.9
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: WmSalesforceRESTProvider
  version: 12.0.0.0.4
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: JMS2waySSL
  gitServerName: rimaSCName
  gitUrl: https://github.com/prabhakarsag
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_191225.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.connections:SoapConnAlias
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.siqa_git_191225.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.connections:RestConnAlias
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.siqa_git_191225.integrations:Call_refData
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.siqa_git_191225.referencedata:refData
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.siqa_git_191225.integrations:Sum
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.0.0.0.693
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.0.0.0.693
- serviceName: project.siqa_git_191225.integrations:Test_RestConnector
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.siqa_git_191225.integrations:Test_SoapConnector
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: project.siqa_git_191225.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.0.0.0.693
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.0.0.0.693
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.0.0.0.693
- serviceName: project.siqa_git_191225.integrations:testjms
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: publisher:publisher
  packages:
  - name: SIQA_GIT_191225Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.9
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.4
- serviceName: jms2wayssl_publisher:jms2wayssl_publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 12.0.0.0.693
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  jdbc.Embedded-Database-Pool.waitingThread: "0"
  jdbcfunc.ISDashboardStats.failFastMode: false
  jdbc.Embedded-Database-Pool.spyenabled: "false"
  jdbcfunc.Xref.failFastMode: true
  jdbcfunc.ISDashboardStats.connPoolAlias: Embedded-Database-Pool
  jdbcfunc.Xref.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.userid: APP
  jdbcfunc.ISInternal.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.password: "{AES}Zcw2EXTJgNDVmVzJO2Y3Bw=="
  jdbc.Embedded-Database-Pool.snoopenabled: "false"
  jdbcfunc.ISInternal.failFastMode: true
  jdbc.Embedded-Database-Pool.maxConns: "10"
  jdbc.Embedded-Database-Pool.expireTime: "60000"
  jdbc.Embedded-Database-Pool.poolThreshold: "0"
  jdbc.Embedded-Database-Pool.useSSL: "false"
  jdbc.Embedded-Database-Pool.minConns: "0"
  jdbc.Embedded-Database-Pool.driverAlias: Embedded Database Driver
  jdbc.Embedded-Database-Pool.dbURL: jdbc:derby:embedded;create=true
